name: Build
on:
  workflow_dispatch:

jobs:
  build-project:
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"
            args: ""
          - platform: "ubuntu-22.04"
            args: ""

    name: Build Project
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Build Project (linux)
        uses: threeal/cmake-action@v2
        with:
          generator: Ninja
