name: Build
on:
  workflow_dispatch:

jobs:
  build-project:
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"
            args: ""
          - platform: "ubuntu-22.04"
            args: ""

    name: Build Project
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Build Project
        uses: threeal/cmake-action@v2
        with:
          generator: Ninja

      - name: Upload artifacts
        if: matrix.platform == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: "cipi8-linux_x86-64"
          path: build/cipi8
          retention-days: 90

      - name: Upload artifacts
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: "cipi8-windows_x64.exe"
          path: build/cipi8.exe
          retention-days: 90
